<?php
namespace MKFramework\Router;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-14 at 17:14:45.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     *
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Factory();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {}

    /**
     * @covers MKFramework\Router\Factory::getRouter
     * 
     * @todo Implement testGetRouter().
     */
    public function testGetRouter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
